# Generated by Django 4.0 on 2022-01-04 12:14

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shortener', '0002_domain_short_link_domain_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='user',
            field=models.OneToOneField(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
