# Generated by Django 4.0 on 2022-01-03 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='short_link',
            field=models.URLField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='domain',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
