# Generated by Django 4.0 on 2022-01-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_alter_domain_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='domain',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='link',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='short_link',
            field=models.URLField(blank=True, max_length=20, unique=True),
        ),
    ]
